<a href="https://colab.research.google.com/github/Rahul711sharma/Classification/blob/main/Telco_Customer_Churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import pandas as pd
import numpy as np
from plotnine import *
import matplotlib.pyplot as plt
import seaborn as sns

In [63]:
from google.colab import drive


In [64]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [65]:
df = pd.read_csv("/content/drive/MyDrive/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [66]:
df.head()

customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [67]:
df.isna().mean()*100

customerID          0.0
gender              0.0
SeniorCitizen       0.0
Partner             0.0
Dependents          0.0
tenure              0.0
PhoneService        0.0
MultipleLines       0.0
InternetService     0.0
OnlineSecurity      0.0
OnlineBackup        0.0
DeviceProtection    0.0
TechSupport         0.0
StreamingTV         0.0
StreamingMovies     0.0
Contract            0.0
PaperlessBilling    0.0
PaymentMethod       0.0
MonthlyCharges      0.0
TotalCharges        0.0
Churn               0.0
dtype: float64

In [68]:
for i in df.columns[1:]:
  print(f"{i}: \n{df[i].value_counts()} \n")

gender: 
Male      3555
Female    3488
Name: gender, dtype: int64 

SeniorCitizen: 
0    5901
1    1142
Name: SeniorCitizen, dtype: int64 

Partner: 
No     3641
Yes    3402
Name: Partner, dtype: int64 

Dependents: 
No     4933
Yes    2110
Name: Dependents, dtype: int64 

tenure: 
1     613
72    362
2     238
3     200
4     176
     ... 
28     57
39     56
44     51
36     50
0      11
Name: tenure, Length: 73, dtype: int64 

PhoneService: 
Yes    6361
No      682
Name: PhoneService, dtype: int64 

MultipleLines: 
No                  3390
Yes                 2971
No phone service     682
Name: MultipleLines, dtype: int64 

InternetService: 
Fiber optic    3096
DSL            2421
No             1526
Name: InternetService, dtype: int64 

OnlineSecurity: 
No                     3498
Yes                    2019
No internet service    1526
Name: OnlineSecurity, dtype: int64 

OnlineBackup: 
No                     3088
Yes                    2429
No internet service    1526
Name: Online

In [70]:
df=df.replace({'No internet service':'No','Yes':1,'No':0,'Month-to-month':0,'Two year':2,'One year':1,'No phone service':0,'Male':0,'Female':1,'DSL':1,'Fiber optic':2,'No':0})

In [71]:
dummies = pd.get_dummies(df['PaymentMethod'],prefix='pay_')
for i in dummies.columns:
  df[i]= dummies[i]
df.drop('PaymentMethod',axis=1,inplace=True)
df.head(3)

customerID  gender  ...  pay__Electronic check  pay__Mailed check
0  7590-VHVEG       1  ...                      1                  0
1  5575-GNVDE       0  ...                      0                  1
2  3668-QPYBK       0  ...                      0                  1

[3 rows x 24 columns]

In [72]:
x = df.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23]]
y = df.iloc[:,19]


In [102]:
sns.heatmap(x)

ValueError: ignored

There is a string value still in the data lets find it

In [120]:
for i in x.columns:
  print(type(x[i][0]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'str'>
<class 'numpy.uint8'>
<class 'numpy.uint8'>
<class 'numpy.uint8'>
<class 'numpy.uint8'>


So the 18th column still have string value

In [121]:
for a,i in enumerate(x['TotalCharges']):
  
  print(a,float(i))



Streaming output truncated to the last 5000 lines.
2043 1043.3
2044 128.6
2045 7455.45
2046 24.7
2047 206.15
2048 2030.3
2049 5869.4
2050 3377.8
2051 1346.2
2052 4946.05
2053 4065.0
2054 106.55
2055 4964.7
2056 4085.75
2057 1742.75
2058 6224.8
2059 3415.25
2060 6325.25
2061 340.25
2062 1683.6
2063 3966.3
2064 608.5
2065 2896.6
2066 1514.85
2067 6792.45
2068 4669.2
2069 95.6
2070 2934.3
2071 6302.8
2072 779.2
2073 283.75
2074 4600.7
2075 5594.0
2076 772.85
2077 71.35
2078 857.8
2079 7554.05
2080 5981.65
2081 1702.9
2082 467.15
2083 20.15
2084 69.75
2085 2931.0
2086 1400.85
2087 137.85
2088 1941.5
2089 1932.75
2090 1423.05
2091 970.85
2092 5810.9
2093 223.9
2094 391.7
2095 79.95
2096 19.3
2097 811.65
2098 174.75
2099 3126.85
2100 6841.45
2101 3754.6
2102 1406.65
2103 834.7
2104 627.4
2105 242.0
2106 3157.0
2107 3092.0
2108 2168.9
2109 980.35
2110 65.95
2111 711.9
2112 1952.8
2113 4368.85
2114 2647.1
2115 8477.6
2116 54.35
2117 4528.0
2118 1790.65
2119 845.6
2120 1210.3
2121 20.45
2122 85

So the 488th row has the string value that's coercing variable to become string

In [116]:
x.iloc[488]['TotalCharges']

' '

In [118]:
x.replace(' ',0,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4389: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,


In [122]:
for i in x['TotalCharges']:
  x['TotalCharges']= float(i)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [132]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

def vif(x):
  vif = pd.DataFrame()
  vif["variables"] = x.columns
  vif["VIF"] = [variance_inflation_factor(x.values, i) for i in range(x.shape[1])]

  return(vif)



In [144]:
x.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'MonthlyCharges',
       'TotalCharges', 'pay__Bank transfer (automatic)',
       'pay__Credit card (automatic)', 'pay__Electronic check',
       'pay__Mailed check'],
      dtype='object')

In [164]:
vif(x[['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'pay__Bank transfer (automatic)',
       'pay__Credit card (automatic)', 'pay__Electronic check',
       'pay__Mailed check']])

variables       VIF
0                           gender  1.001509
1                    SeniorCitizen  1.152249
2                          Partner  1.461997
3                       Dependents  1.383544
4                           tenure  2.729148
5                     PhoneService  1.148409
6                    MultipleLines  1.416247
7                  InternetService  2.232338
8                   OnlineSecurity  1.287407
9                     OnlineBackup  1.344886
10                DeviceProtection  1.456482
11                     TechSupport  1.372853
12                     StreamingTV  1.624595
13                 StreamingMovies  1.631600
14                        Contract  2.442792
15                PaperlessBilling  1.207742
16  pay__Bank transfer (automatic)  5.054142
17    pay__Credit card (automatic)  4.944476
18           pay__Electronic check  6.957551
19               pay__Mailed check  4.248501

In [165]:
x =x[['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'pay__Bank transfer (automatic)',
       'pay__Credit card (automatic)', 'pay__Electronic check',
       'pay__Mailed check']]

In [171]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(5282, 20)
(5282,)
(1761, 20)
(1761,)


In [175]:
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()
logit.fit(x_train,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0, 0, 0, ..., 0, 0, 0])

In [176]:
#Model accuracy on train data

pred_self = logit.predict(x_train)
pred_self

array([0, 0, 0, ..., 0, 0, 0])

In [182]:
pd.pivot_table(pd.DataFrame({'y_train':y_train,'pred_self':pred_self}),index=y_train,columns=pred_self,aggfunc='count')

pred_self      y_train     
              0    1       0    1
Churn                            
0          3533  380    3533  380
1           647  722     647  722

In [184]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,pred_self)

array([[3533,  380],
       [ 647,  722]])

In [187]:
print(f"accuracy : {(3533+722)/(3533+722+647+380)}")
print(f"recall : {722/(722+647)}")
print(f"precision : {722/(380+722)}")

accuracy : 0.8055660734570238
recall : 0.5273922571219869
precision : 0.6551724137931034


In [190]:
#model Accuracy on test Data
test_pred = logit.predict(x_test)

In [191]:
pd.pivot_table(pd.DataFrame({'y_test':y_test,'test_pred':test_pred}),index=y_test,columns=test_pred,aggfunc='count')

test_pred      y_test     
              0    1      0    1
Churn                           
0          1135  126   1135  126
1           228  272    228  272

In [192]:
print(f"accuracy : {(1135+272)/(1135+272+126+228)}")

accuracy 0.7989778534923339
